/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(linear_fm_waveform.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(59bc0d58b36b13c76ec83691275a6774)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <plasma/linear_fm_waveform.h>
// pydoc.h is automatically generated in the build directory
#include <linear_fm_waveform_pydoc.h>

void bind_linear_fm_waveform(py::module& m)
{

    using linear_fm_waveform    = gr::plasma::linear_fm_waveform;


    py::class_<linear_fm_waveform,
        std::shared_ptr<linear_fm_waveform>>(m, "linear_fm_waveform", D(linear_fm_waveform))

        .def(py::init(&linear_fm_waveform::make),
           py::arg("bandwidth"),
           py::arg("pulsewidth"),
           py::arg("prf"),
           py::arg("samp_rate"),
           D(linear_fm_waveform,make)
        )
        



        ;




}








