/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_to_stream_repeat.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(212daee3413dcaa65ff7d2afbbd4cd41)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/pdu_to_stream_repeat.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_to_stream_repeat_pydoc.h>

void bind_pdu_to_stream_repeat(py::module& m)
{

    using pdu_to_stream_repeat    = ::gr::plasma::pdu_to_stream_repeat;


    py::class_<pdu_to_stream_repeat, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pdu_to_stream_repeat>>(m, "pdu_to_stream_repeat", D(pdu_to_stream_repeat))

        .def(py::init(&pdu_to_stream_repeat::make),
           D(pdu_to_stream_repeat,make)
        )
        



        ;




}








