/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(repeat_pdu_to_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a6063ca32f016d2970b2071c89b50860)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/plasma/repeat_pdu_to_stream.h>
// pydoc.h is automatically generated in the build directory
#include <repeat_pdu_to_stream_pydoc.h>

void bind_repeat_pdu_to_stream(py::module& m)
{

    using repeat_pdu_to_stream    = gr::plasma::repeat_pdu_to_stream;


       py::class_<repeat_pdu_to_stream,
              gr::sync_block,
              gr::block,
              gr::basic_block,
              std::shared_ptr<repeat_pdu_to_stream>>(m, "repeat_pdu_to_stream", D(repeat_pdu_to_stream))

        .def(py::init(&repeat_pdu_to_stream::make),
           D(repeat_pdu_to_stream,make)
        )
        



        ;




}








